### ISSUE TITLE
Edits for columbia scrolly

### ISSUE THREAD

**Issue by squirrelsquirrel78** [spec-journalism/ivy-coronavirus-response#2]
## Illustrator

- [x] Minimum font size of 14px, except `SPRING BREAK`
- [x] Relabel "1 case in New York" to "first case in New York"?
- [x] I think we can remove the Barnard annotation.
- [x] Lift the radius of the date circle marker to 7
- [x] Add a little spacing here: 
![image](https://user-images.githubusercontent.com/15334952/79009619-e8efdd00-7b2d-11ea-952e-d93d62b4acbe.png)
- [ ] I think we can remove the dotted line/solid line distinction and just use solid lines.

## HTML/CSS

- [x] `p.first_text desk`: try to mirror the styles of `.lede-step > p` (rule set is in `styles/lede-chart.scss`).

- [x] `.scroll_text`, `.steps`, and `.steps > p`:
  * Getting the same or a close width/max-width on the paragraph as in `.lede-step > p` would be ideal. It's okay if the `p` itself leaks onto the ai2html a bit.

- [x] It's not clear what date corresponds to the last step.

- [x] Replacing top margins with vertical alignment:
  * Set `.scroll__graphic` top to 0 and remove `margin-top` on `#g-columbia-desktop`. Make `.chart`'s height the full view height, add a display flex, and align items center.
    * Don't use `100vh` (see https://github.com/russellgoldenberg/scrollama#tips)

- [x] I don't think you need to set the percentage width of the `.chart` because every ai2html artboard stuff sets its own width in pixels

**Comment by shallotly** [comment]
![IMG_7301](https://user-images.githubusercontent.com/56002814/79010134-518b8980-7b2f-11ea-8cb5-e3b81fb5dff9.JPG)
