### ISSUE TITLE
Columbia graphic more ideas

### ISSUE THREAD

**Issue by squirrelsquirrel78** [spec-journalism/ivy-coronavirus-response#4]
## 1

![image](https://user-images.githubusercontent.com/15334952/79049693-1e123300-7bf3-11ea-93f4-56ab085a0c30.png)

I think we can remove the kinda awkward Columbia subhed and just go straight into  the scrolly graphic. Here's how I think we can add back the context that the subhed used to give:
* Make "First case in New York" more apparent, especially the New York part
* In the first step, change "On March 8, President Lee Bollinger announced the University would…" to "On March 8, President Lee Bollinger announced Columbia would…"

## 2

![image](https://user-images.githubusercontent.com/15334952/79049771-8bbe5f00-7bf3-11ea-8eae-2bb3103a6091.png)

Since this highlighted part of the text directly corresponds to an annotation in the graphic, I think we should highlight the keywords in the text (e.g. "canceled classes") while making the graphic's "Classes canceled" text more apparent (i.e. larger, higher font weight). Possibly fade that entire annotation in with "March 8" as well.

## 3

![image](https://user-images.githubusercontent.com/15334952/79049867-08513d80-7bf4-11ea-9a35-3ddae1394e28.png)

Change the artboard width to just fit the graphic — remove the horizontal padding.

## 4

For all the school artboards:
* Make the "1 case in _STATE_" larger and more apparent.
* "Classes canceled/suspended/etc." labels should be more apparent like mentioned in part 2. Leave spring break labels unchanged.
* Raise line height of annotations to 17px

## 5

![image](https://user-images.githubusercontent.com/15334952/79050137-038d8900-7bf6-11ea-898d-0361873f840b.png)

On this graphic's 300, change line height to 20px.

Can we also make the circles of the entire graphic larger and the stroke width of all red/pink lines lower

**Comment by raeedahw** [comment]
k

**Comment by squirrelsquirrel78** [comment]
![image](https://user-images.githubusercontent.com/15334952/79058740-adddce80-7c3f-11ea-85ca-5dfd36a84d26.png)

**Comment by raeedahw** [comment]
is your nose never not bleeding?
